name: Build with Maven and generate reports

on: [push,pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
      continue-on-error: true
      
    - name: Test with JaCoCo
      run: mvn test jacoco:report
      continue-on-error: true
      
    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: mvn coveralls:report

    - name: Create site
      run: mvn site

    - name: Ensure index.html exists
      run: |
        if [ ! -f target/site/index.html ]; then
          echo "<html><body><h1>Report Index</h1></body></html>" > target/site/index.html
        fi

    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site
